# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "activemerchant_alipay"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lkhagva Ochirkhuyag"]
  s.date = "2012-02-22"
  s.description = "Activemerchant patch for china online payment platform alipay"
  s.email = "ochkoo@gmail.com"
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION",
    "activemerchant_alipay.gemspec",
    "init.rb",
    "lib/active_merchant/billing/integrations/alipay.rb",
    "lib/active_merchant/billing/integrations/alipay/common.rb",
    "lib/active_merchant/billing/integrations/alipay/helper.rb",
    "lib/active_merchant/billing/integrations/alipay/notification.rb",
    "lib/active_merchant/billing/integrations/alipay/return.rb",
    "lib/activemerchant_alipay.rb",
    "test/activemerchant_alipay_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/ochko/activemerchant_alipay"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Activemerchant integration for Alipay"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activemerchant>, [">= 1.20.0"])
    else
      s.add_dependency(%q<activemerchant>, [">= 1.20.0"])
    end
  else
    s.add_dependency(%q<activemerchant>, [">= 1.20.0"])
  end
end

